# NumPy Tutorial

In [5]:
import numpy as np

## The Basics

In [2]:
a = [1, 2, 3]
print(a)
print(type(a))

[1, 2, 3]
<class 'list'>


In [6]:
a = np.array(a)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
# We can also create arrays of different dimensions in numpy
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(type(b))

<class 'numpy.ndarray'>


In [9]:
# we can see the dimension of any nump array using the .shape command
print(b.shape)

(2, 3)


In [10]:
print(a.shape)

(3,)


## Creating arrays using `Numpy.random` package

In [24]:
r = np.random.randint(100, size=(4, 10))
print(r)

[[69 47 12 80 72 21 58 11 70 56]
 [28 70 59  6 96 75 87 23 86 95]
 [53 77 75 25 27 62 78 80 13 12]
 [46 78 45 35 55  7 18 75 94 49]]


In [27]:
r2 = np.random.rand(3, 4)
print(r2)

[[0.91474156 0.59824563 0.61696441 0.87449874]
 [0.38074045 0.56002924 0.76406143 0.28856025]
 [0.8152455  0.2134286  0.42343823 0.82897078]]


## Accessing Specific Elements

In [28]:
r = np.random.randint(10, size=(3, 4))
print(r)

[[5 7 0 3]
 [5 6 0 5]
 [1 5 3 4]]


In [31]:
# accessing first row
print(r[0, ])

[5 7 0 3]


In [30]:
# accessing last row
print(r[-1, ])

[1 5 3 4]


In [32]:
# accessing specific row
row = 2
print(r[row - 1, ])

[5 6 0 5]


In [37]:
# accessing the first column
print(r[:, 0])

[5 5 1]


In [39]:
# accessing the last column and reshaping it into a column vector
c1 = r[:, 0]
print(c1)
c1 = c1.reshape((3, 1))
print(c1)

[5 5 1]
[[5]
 [5]
 [1]]


In [40]:
# accessing the last column
c2 = r[:, -1]
print(c2)

[3 5 4]


In [42]:
# reshaping the last column into column vector
c2 = c2.reshape((3, 1))
print(c2)

[[3]
 [5]
 [4]]


In [52]:
# retreiving specific rows
r = np.random.randint(low=0, high=100, size=(5, 6))
print(r)

[[68 21 79 25 80 11]
 [73 41 29 84 50 83]
 [86 15 65 40 97 55]
 [25 99  4 52 65 95]
 [22  6 87 98 76 84]]


In [53]:
print(r[[0, 1], :])

[[68 21 79 25 80 11]
 [73 41 29 84 50 83]]


In [54]:
# printing selected rows
print(r[[0, 3], ])

[[68 21 79 25 80 11]
 [25 99  4 52 65 95]]


In [55]:
# changing order of rows
print(r[[3, 0, 4], ])

[[25 99  4 52 65 95]
 [68 21 79 25 80 11]
 [22  6 87 98 76 84]]


In [58]:
# getting specific columns
print(r[:, [4, 2]])

[[80 79]
 [50 29]
 [97 65]
 [65  4]
 [76 87]]


In [59]:
# selecting a specific element (row, column)
print(r[0, 0])

68


In [60]:
row, column = 2, 3
print(r[row, column])

40


In [ ]:
# getting elements 